//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ТелекомНеваСвязь
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictsAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistrictsAddress()
        {
            this.Address = new HashSet<Address>();
        }
    
        public int DistrictsID { get; set; }
        public string DistrictsName { get; set; }
        public double DistrictSquare { get; set; }
        public int DistrictPopulation { get; set; }
        public int DistrictMetro { get; set; }
        public int DistrictBuildingType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        public virtual TypeOfBuilding TypeOfBuilding { get; set; }
    }
}
