//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ТелекомНеваСвязь
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int IDInformation { get; set; }
        public int IDRole { get; set; }
        public string Information1 { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
