//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ТелекомНеваСвязь
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportData
    {
        public string IDSubscriber { get; set; }
        public int Series { get; set; }
        public int Number { get; set; }
        public string PassportCode { get; set; }
        public string PassportIssued { get; set; }
        public System.DateTime PassportDateIssued { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
    }
}
