//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ТелекомНеваСвязь
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTreaty
    {
        public int IDServiceTreaty { get; set; }
        public int ServiceID { get; set; }
        public string TreatyID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Treaty Treaty { get; set; }
    }
}
