//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ТелекомНеваСвязь
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public string IDSubscriber { get; set; }
        public string SubscriberSurname { get; set; }
        public string SubscriberName { get; set; }
        public string SubscriberPatronymic { get; set; }
        public int Genre { get; set; }
        public System.DateTime Birthday { get; set; }
        public string NumberPhone { get; set; }
        public string Email { get; set; }
        public int AddressRegistration { get; set; }
        public int AddressAccommodation { get; set; }
        public string IDTreaty { get; set; }
        public int SubscriberEquipment { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Equipments Equipments { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual PassportData PassportData { get; set; }
        public virtual Treaty Treaty { get; set; }
    }
}
