
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ТелекомНеваСвязь
{

using System;
    using System.Collections.Generic;
    
public partial class Treaty
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Treaty()
    {

        this.ServiceTreaty = new HashSet<ServiceTreaty>();

        this.Subscriber = new HashSet<Subscriber>();

    }


    public string TreatyNumber { get; set; }

    public System.DateTime TreatyDateСonclusion { get; set; }

    public int TreatyType { get; set; }

    public Nullable<int> ReasonForTermination { get; set; }

    public Nullable<System.DateTime> TreatyTerminationDate { get; set; }

    public int TreatyPersonalAccount { get; set; }



    public virtual ReasonForTermination ReasonForTermination1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ServiceTreaty> ServiceTreaty { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Subscriber> Subscriber { get; set; }

    public virtual TypeTreaty TypeTreaty { get; set; }

}

}
